name: Validate GLEE Dataset

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: read
  id-token: write
  attestations: write

jobs:
  validate:
    uses: tscnlab/glee-metadata-validator/.github/workflows/validate.yml@v0.4.3
    with:
      datapackage: datapackage.json
